# Define the functions directory
[build]
  functions = "functions/api"

# Redirect requests to the PHP file in the functions directory
[[redirects]]
  from = "/api/submit.php"
  to = "/.netlify/functions/api/submit.php"
  status = 200

# Define environment variables
[build.environment]
  PHP_VERSION = "7.4"

# Add comments to explain each section
# Define the functions directory
# Redirect requests to the PHP file in the functions directory
# Define environment variables
